### ISSUE TITLE
Outdated 'yum-epel' dependency

### ISSUE THREAD

**Issue by chenpdx** [rylarson/chef-entropy#2]
The outdated depends 'yum-epel', '<= 0.6.0' dependency should be removed. It causes 'dependency conflict' with other cookbooks that use later version of yum-epel.

**Comment by darkweasel77** [comment]
See #3

**Comment by darkweasel77** [comment]
@rylarson do you have a path to update chef.io easily?

**Comment by rylarson** [comment]
@darkweasel77, yes I do. I will push a release today.

**Comment by darkweasel77** [comment]
Thanks!

**Comment by darkweasel77** [comment]
@rylarson It doesn't look like a release ever got pushed to supermarket?

**Comment by ChiefAlexander** [comment]
This still needs to be released. Anyway we can get it released @rylarson

**Comment by rylarson** [comment]
Sorry for the delay, I could have sworn I had already released it. It has been done.

**Comment by ChiefAlexander** [comment]
Thanks @rylarson!
